// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tasks_api.proto

package tasksApi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AddTaskReq struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskReq) Reset()         { *m = AddTaskReq{} }
func (m *AddTaskReq) String() string { return proto.CompactTextString(m) }
func (*AddTaskReq) ProtoMessage()    {}
func (*AddTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{1}
}

func (m *AddTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskReq.Unmarshal(m, b)
}
func (m *AddTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskReq.Marshal(b, m, deterministic)
}
func (m *AddTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskReq.Merge(m, src)
}
func (m *AddTaskReq) XXX_Size() int {
	return xxx_messageInfo_AddTaskReq.Size(m)
}
func (m *AddTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskReq proto.InternalMessageInfo

func (m *AddTaskReq) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateTaskReq struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskReq) Reset()         { *m = UpdateTaskReq{} }
func (m *UpdateTaskReq) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskReq) ProtoMessage()    {}
func (*UpdateTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{2}
}

func (m *UpdateTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskReq.Unmarshal(m, b)
}
func (m *UpdateTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskReq.Marshal(b, m, deterministic)
}
func (m *UpdateTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskReq.Merge(m, src)
}
func (m *UpdateTaskReq) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskReq.Size(m)
}
func (m *UpdateTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskReq proto.InternalMessageInfo

func (m *UpdateTaskReq) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type DeleteTaskReq struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskReq) Reset()         { *m = DeleteTaskReq{} }
func (m *DeleteTaskReq) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskReq) ProtoMessage()    {}
func (*DeleteTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{3}
}

func (m *DeleteTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskReq.Unmarshal(m, b)
}
func (m *DeleteTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskReq.Marshal(b, m, deterministic)
}
func (m *DeleteTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskReq.Merge(m, src)
}
func (m *DeleteTaskReq) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskReq.Size(m)
}
func (m *DeleteTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskReq proto.InternalMessageInfo

func (m *DeleteTaskReq) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type ListTasksReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksReq) Reset()         { *m = ListTasksReq{} }
func (m *ListTasksReq) String() string { return proto.CompactTextString(m) }
func (*ListTasksReq) ProtoMessage()    {}
func (*ListTasksReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{4}
}

func (m *ListTasksReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksReq.Unmarshal(m, b)
}
func (m *ListTasksReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksReq.Marshal(b, m, deterministic)
}
func (m *ListTasksReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksReq.Merge(m, src)
}
func (m *ListTasksReq) XXX_Size() int {
	return xxx_messageInfo_ListTasksReq.Size(m)
}
func (m *ListTasksReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksReq proto.InternalMessageInfo

type PingReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{5}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

type AddTaskResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskResp) Reset()         { *m = AddTaskResp{} }
func (m *AddTaskResp) String() string { return proto.CompactTextString(m) }
func (*AddTaskResp) ProtoMessage()    {}
func (*AddTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{6}
}

func (m *AddTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskResp.Unmarshal(m, b)
}
func (m *AddTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskResp.Marshal(b, m, deterministic)
}
func (m *AddTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskResp.Merge(m, src)
}
func (m *AddTaskResp) XXX_Size() int {
	return xxx_messageInfo_AddTaskResp.Size(m)
}
func (m *AddTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskResp proto.InternalMessageInfo

func (m *AddTaskResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type UpdateTaskResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskResp) Reset()         { *m = UpdateTaskResp{} }
func (m *UpdateTaskResp) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskResp) ProtoMessage()    {}
func (*UpdateTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{7}
}

func (m *UpdateTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskResp.Unmarshal(m, b)
}
func (m *UpdateTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskResp.Marshal(b, m, deterministic)
}
func (m *UpdateTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskResp.Merge(m, src)
}
func (m *UpdateTaskResp) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskResp.Size(m)
}
func (m *UpdateTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskResp proto.InternalMessageInfo

func (m *UpdateTaskResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type DeleteTaskResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskResp) Reset()         { *m = DeleteTaskResp{} }
func (m *DeleteTaskResp) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskResp) ProtoMessage()    {}
func (*DeleteTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{8}
}

func (m *DeleteTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskResp.Unmarshal(m, b)
}
func (m *DeleteTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskResp.Marshal(b, m, deterministic)
}
func (m *DeleteTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskResp.Merge(m, src)
}
func (m *DeleteTaskResp) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskResp.Size(m)
}
func (m *DeleteTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskResp proto.InternalMessageInfo

func (m *DeleteTaskResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ListTasksResp struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksResp) Reset()         { *m = ListTasksResp{} }
func (m *ListTasksResp) String() string { return proto.CompactTextString(m) }
func (*ListTasksResp) ProtoMessage()    {}
func (*ListTasksResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{9}
}

func (m *ListTasksResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksResp.Unmarshal(m, b)
}
func (m *ListTasksResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksResp.Marshal(b, m, deterministic)
}
func (m *ListTasksResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksResp.Merge(m, src)
}
func (m *ListTasksResp) XXX_Size() int {
	return xxx_messageInfo_ListTasksResp.Size(m)
}
func (m *ListTasksResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksResp proto.InternalMessageInfo

func (m *ListTasksResp) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type PingResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResp) Reset()         { *m = PingResp{} }
func (m *PingResp) String() string { return proto.CompactTextString(m) }
func (*PingResp) ProtoMessage()    {}
func (*PingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf5f6b16ea9d1f8, []int{10}
}

func (m *PingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResp.Unmarshal(m, b)
}
func (m *PingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResp.Marshal(b, m, deterministic)
}
func (m *PingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResp.Merge(m, src)
}
func (m *PingResp) XXX_Size() int {
	return xxx_messageInfo_PingResp.Size(m)
}
func (m *PingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResp.DiscardUnknown(m)
}

var xxx_messageInfo_PingResp proto.InternalMessageInfo

func (m *PingResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Task)(nil), "tasksApi.Task")
	proto.RegisterType((*AddTaskReq)(nil), "tasksApi.AddTaskReq")
	proto.RegisterType((*UpdateTaskReq)(nil), "tasksApi.UpdateTaskReq")
	proto.RegisterType((*DeleteTaskReq)(nil), "tasksApi.DeleteTaskReq")
	proto.RegisterType((*ListTasksReq)(nil), "tasksApi.ListTasksReq")
	proto.RegisterType((*PingReq)(nil), "tasksApi.PingReq")
	proto.RegisterType((*AddTaskResp)(nil), "tasksApi.AddTaskResp")
	proto.RegisterType((*UpdateTaskResp)(nil), "tasksApi.UpdateTaskResp")
	proto.RegisterType((*DeleteTaskResp)(nil), "tasksApi.DeleteTaskResp")
	proto.RegisterType((*ListTasksResp)(nil), "tasksApi.ListTasksResp")
	proto.RegisterType((*PingResp)(nil), "tasksApi.PingResp")
}

func init() { proto.RegisterFile("tasks_api.proto", fileDescriptor_daf5f6b16ea9d1f8) }

var fileDescriptor_daf5f6b16ea9d1f8 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x0d, 0xa5, 0xf2, 0x31, 0x95, 0x1a, 0x27, 0x08, 0x4d, 0x4f, 0x64, 0xa3, 0x09, 0x17, 0x8a,
	0x81, 0xe8, 0xc9, 0xc4, 0x60, 0x3c, 0x72, 0x30, 0x55, 0x2f, 0x5e, 0x4c, 0xa5, 0x1b, 0xb2, 0x41,
	0xcb, 0xc2, 0xac, 0xfe, 0x32, 0x7f, 0xa0, 0xe9, 0xf2, 0xb1, 0x0b, 0xa9, 0x24, 0xdc, 0xb6, 0x6f,
	0xde, 0xbc, 0x79, 0x33, 0x2f, 0x85, 0x33, 0x95, 0xd0, 0x8c, 0xde, 0x13, 0x29, 0x22, 0xb9, 0x9c,
	0xab, 0x39, 0xd6, 0x34, 0x30, 0x92, 0x82, 0x8d, 0xc1, 0x7d, 0x49, 0x68, 0x86, 0x3e, 0x38, 0x22,
	0x0d, 0x4a, 0x9d, 0x52, 0xb7, 0x1e, 0x3b, 0x22, 0x45, 0x04, 0x37, 0x4b, 0xbe, 0x78, 0xe0, 0x68,
	0x44, 0xbf, 0xb1, 0x03, 0x5e, 0xca, 0x69, 0xb2, 0x14, 0x52, 0x89, 0x79, 0x16, 0x94, 0x75, 0xc9,
	0x86, 0xd8, 0x35, 0xc0, 0x28, 0x4d, 0x73, 0xc1, 0x98, 0x2f, 0x90, 0x81, 0x9b, 0xcf, 0xd1, 0xaa,
	0xde, 0xc0, 0x8f, 0x36, 0x43, 0x23, 0x4d, 0xd0, 0x35, 0x36, 0x84, 0xc6, 0xab, 0x4c, 0x13, 0xc5,
	0x8f, 0x6c, 0x7a, 0xe4, 0x9f, 0xfc, 0xb8, 0x26, 0x1f, 0x4e, 0xc7, 0x82, 0x54, 0x8e, 0x50, 0xcc,
	0x17, 0xac, 0x0e, 0xd5, 0x27, 0x91, 0x4d, 0xf3, 0xe7, 0x15, 0x78, 0x5b, 0xdb, 0x24, 0xb1, 0x05,
	0x15, 0x52, 0x89, 0xfa, 0x26, 0xad, 0x57, 0x8b, 0xd7, 0x5f, 0xac, 0x0b, 0xbe, 0xed, 0xf5, 0x30,
	0xd3, 0x36, 0x78, 0x80, 0x79, 0x03, 0x0d, 0xcb, 0x15, 0x49, 0xbc, 0x84, 0x13, 0xed, 0x3e, 0x28,
	0x75, 0xca, 0x05, 0xbb, 0xac, 0x8a, 0x8c, 0x41, 0x6d, 0x65, 0xfe, 0x7f, 0xe9, 0xc1, 0xaf, 0x03,
	0x5e, 0xde, 0xf3, 0xcc, 0x97, 0x3f, 0x62, 0xc2, 0xf1, 0x16, 0xaa, 0xeb, 0x2d, 0xb1, 0x69, 0x54,
	0x4d, 0x5e, 0xe1, 0x45, 0x01, 0x4a, 0x12, 0xef, 0x01, 0xcc, 0xda, 0xd8, 0x36, 0xa4, 0x9d, 0xe0,
	0xc2, 0xa0, 0xb8, 0xb0, 0x12, 0x30, 0xd7, 0xb0, 0x05, 0x76, 0x42, 0xb4, 0x05, 0xf6, 0x8e, 0x77,
	0x07, 0xf5, 0xed, 0x91, 0xb0, 0x65, 0x68, 0x76, 0x9e, 0x61, 0xbb, 0x10, 0x27, 0x89, 0x3d, 0x70,
	0xf3, 0x5b, 0xe1, 0xb9, 0x21, 0xac, 0x83, 0x0f, 0x71, 0x1f, 0x22, 0xf9, 0xd0, 0x7a, 0x6b, 0x46,
	0x7d, 0xfd, 0x9b, 0xf4, 0xa6, 0x3c, 0xeb, 0x6f, 0x08, 0x1f, 0x15, 0x8d, 0x0d, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x27, 0x26, 0x22, 0x14, 0x4d, 0x03, 0x00, 0x00,
}
